# This is a basic workflow to help you get started with Actions

name: email login

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Which Job to Run.'
        required: true
        default: 'cbcregression'
      environmentName:
        description: 'Name of the environment'
        required: true
        default: 'cbc-tst.app.corpintra.net/'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cbcregression:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      env:
        AFAAS_NPM_USER: ${{ secrets.EMAIL_USERNAME }}
        Password: ${{ secrets.EMAIL_PASSWORD }}

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v4

        # Runs a single command using the runners shell
        - name: Run a one-line script
          run: echo Hello, world!

        # Runs a set of commands using the runners shell
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
